CREATE TABLE IF NOT EXISTS 'users'
(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username VARCHAR(80) NOT NULL,
    password VARCHAR(500) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone INTEGER,
    created_date DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS 'orders'
(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    created_date DATETIME NOT NULL
);

-- CHECK (mycolumn IN (0,1)
