from .order_history import make_order_history_route
from .cart import make_cart_route
from .change_password import make_change_password_route
from .checkout import make_checkout_route
from .index import make_index_route
from .logout import make_logout_route
from .register import make_register_route
from .product_page import make_product_page_route
from .login import make_login_route
